const $=s=>document.querySelector(s),fmt=new Intl.NumberFormat('zh-HK');let analysisStartYear=1998,analysisEndYear=new Date().getFullYear();
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const months=['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'];
const dur=m=>m<60?`${m}分鐘`:`${Math.floor(m/60)}小時${m%60?m%60+'分':''}`;
const warningHref=id=>window.THUNDER_STATIC?`index.html?q=${encodeURIComponent(id)}`:`/warnings/${encodeURIComponent(id)}`;
const hbars=(rows,label='label')=>{const max=Math.max(1,...rows.map(x=>x.count));return rows.map(x=>`<div class="hbar"><span>${esc(x[label])}</span><div class="hbar-track"><i style="--width:${x.count/max*100}%"></i></div><span>${fmt.format(x.count)}</span></div>`).join('')};
async function init(){const r=await fetch('/api/analysis');if(!r.ok)throw new Error(`HTTP ${r.status}`);const d=await r.json();analysisStartYear=+d.generated_from.bulletin_start_year;analysisEndYear=+d.generated_from.bulletin_end_year;render(d);$('#analysisLoading').hidden=true;$('#analysisContent').hidden=false}
function render(d){
  $('#analysisStats').innerHTML=[['警告系列',d.generated_from.series],['天氣稿事件',d.generated_from.events],['提早取消',d.cancellations.count],['有天氣稿可分析',d.extensions.analysed_series]].map(([l,v],i)=>`<div class="stat"><div class="stat-value ${i===1?'stat-accent':''}">${fmt.format(v)}</div><div class="stat-label">${l}</div></div>`).join('');
  $('#analysisUpdated').textContent=`分析生成：${new Intl.DateTimeFormat('zh-HK',{dateStyle:'medium',timeStyle:'short',timeZone:'Asia/Hong_Kong'}).format(new Date(d.generated_from.generated_at))}`;
  const maxHeat=Math.max(...d.behavior.heatmap.flat());let heat='<span></span>'+Array.from({length:24},(_,h)=>`<span class="hm-hour">${h%3===0?h:''}</span>`).join('');d.behavior.heatmap.forEach((row,m)=>{heat+=`<span class="hm-label">${months[m]}</span>`+row.map((v,h)=>`<button class="hm-cell" style="--level:${v/maxHeat}" title="${months[m]} ${h}:00：${v}組" aria-label="${months[m]} ${h}:00，${v}組警告"></button>`).join('')});$('#heatmap').innerHTML=heat;
  $('#durationBuckets').innerHTML=hbars(d.behavior.duration_buckets);const ds=d.behavior.duration_summary;$('#durationSummary').innerHTML=micro([['中位數',dur(ds.median)],['九成不超過',dur(ds.p90)],['最長',dur(ds.maximum)]]);$('#durationTrend').innerHTML=lineSvg(d.behavior.duration_trend,'average','median');
  $('#extensionBars').innerHTML=hbars(Object.entries(d.extensions.distribution).map(([label,count])=>({label:label+'次',count})));$('#cancelSummary').innerHTML=`延長分析只包括 <strong>${fmt.format(d.extensions.analysed_series)}</strong> 組有天氣稿警告；另有 <strong>${fmt.format(d.extensions.unknown_series)}</strong> 組資料不足。<br>提早取消幅度中位數係 <strong>${dur(d.cancellations.median_margin)}</strong>；九成個案不超過 <strong>${dur(d.cancellations.p90_margin)}</strong>。`;
  $('#complexTable').innerHTML=`<div class="ranked-row table-head"><b>排名</b><strong>警告系列</strong><span>事件數</span><span>延長次數</span></div>`+d.extensions.top_complex.slice(0,8).map((x,i)=>`<div class="ranked-row"><b>#${i+1}</b><strong><a href="${warningHref(x.id)}">${esc(x.id)}</a></strong><span>${x.events} 個</span><span>${x.extensions} 次</span></div>`).join('');
  $('#cancelTable').innerHTML=`<div class="ranked-row table-head"><b>排名</b><strong>警告系列</strong><span>開始日期</span><span>提早取消幅度</span></div>`+d.cancellations.top.map((x,i)=>`<div class="ranked-row"><b>#${i+1}</b><strong><a href="${warningHref(x.id)}">${esc(x.id)}</a></strong><span>${x.started_at.slice(0,10)}</span><span>早 ${dur(x.minutes)}</span></div>`).join('');
  $('#placeBars').innerHTML=hbars(d.geography,'place');$('#placeMethod').innerHTML=`成功分類 ${fmt.format(d.geography_method.classified_bulletins)} 份稿；未能分類 ${fmt.format(d.geography_method.unclassified_bulletins)} 份；同時涉及多區 ${fmt.format(d.geography_method.multi_region_bulletins)} 份。`;$('#placeTrends').innerHTML=sparkRows(d.geography.map(x=>({label:x.place,yearly:x.yearly,count:x.count})));$('#hazardStats').innerHTML=micro(d.hazards.terms.map(x=>[x.label,fmt.format(x.count)]));$('#hazardMethod').textContent=d.hazards.terms.map(x=>`${x.label}：${fmt.format(x.count)}組／${fmt.format(x.bulletin_count)}份稿`).join(' · ');$('#hazardTrends').innerHTML=sparkRows(d.hazards.terms.map(x=>({label:x.label,yearly:x.years,count:x.count})));$('#gustTable').innerHTML=d.hazards.top_gusts.slice(0,7).map(x=>row(`<a target="_blank" href="${x.source_url}">${x.speed} km/h</a>`,x.at.slice(0,10),x.series_id||'未配對')).join('');
  const tMin=analysisStartYear,tMax=analysisEndYear;$('#templateRows').innerHTML=d.templates.map(x=>`<div class="template-row"><span>${x.label}</span><div class="template-line"><i style="--left:${(+x.first-tMin)/(tMax-tMin)*100}%;--width:${(+x.last-+x.first)/(tMax-tMin)*100}%"></i></div><strong>${fmt.format(x.count)}</strong></div>`).join('');
  $('#coverageChart').innerHTML=d.quality.by_year.map(x=>{const total=Object.entries(x).filter(([k])=>k!=='year').reduce((s,[,v])=>s+v,0);return `<div class="coverage-year" title="${x.year}">${['available','archive_incomplete','not_downloaded','not_archived'].map(k=>`<i class="${k}" style="height:${(x[k]||0)/total*100}%"></i>`).join('')}</div>`}).join('');$('#qualitySummary').innerHTML=`天氣稿開始時間與官方系列不同：<strong>${d.quality.different_start_count}</strong>份；更正稿：<strong>${d.quality.corrections}</strong>份；未能配對官方系列：<strong>${d.quality.unmatched}</strong>份。`;
  renderClimate(d.climate);$('#anomalyTable').innerHTML=`<div class="table-row table-head"><strong>警告系列</strong><span>天氣稿刊登時間</span><span>開始時間差異</span><span>政府原文</span></div>`+d.quality.largest_start_deltas.map(x=>{const id=x.warning_series_id;return `<div class="table-row"><strong>${id?`<a href="${warningHref(id)}">${esc(id)}</a>`:'未配對'}</strong><span>${x.bulletin_at.slice(0,16).replace('T',' ')}</span><span>相差 ${x.official_start_delta_minutes} 分鐘</span><a target="_blank" rel="noopener" href="${x.source_url}">原文 ↗</a></div>`}).join('');
}
function micro(rows){return rows.map(([l,v])=>`<div class="micro-stat"><strong>${v}</strong><span>${l}</span></div>`).join('')}
function row(a,b,c){return `<div class="table-row"><strong>${a}</strong><span>${b}</span><span>${c}</span></div>`}
function sparkRows(rows){return rows.map(x=>{const years=Array.from({length:analysisEndYear-analysisStartYear+1},(_,i)=>String(analysisStartYear+i)),max=Math.max(1,...years.map(y=>x.yearly[y]||0));return `<div class="spark-row"><span>${esc(x.label)}</span><div class="spark">${years.map(y=>`<i tabindex="0" role="img" aria-label="${esc(x.label)} ${y}年 ${x.yearly[y]||0}組" style="--v:${(x.yearly[y]||0)/max}" title="${y}：${x.yearly[y]||0}"></i>`).join('')}</div><strong>${fmt.format(x.count)}</strong></div>`}).join('')}
function lineSvg(rows,keyA,keyB){
  const maxRaw=Math.max(...rows.flatMap(x=>[x[keyA],x[keyB]])),max=Math.ceil(maxRaw/60)*60,minY=+rows[0].year,maxY=+rows.at(-1).year,left=65,right=680,top=18,bottom=235;
  const x=row=>left+(+row.year-minY)/(maxY-minY)*(right-left),y=value=>bottom-value/max*(bottom-top),points=key=>rows.map(row=>`${x(row)},${y(row[key])}`).join(' ');
  const grids=Array.from({length:5},(_,i)=>{const value=max*(4-i)/4,yy=y(value);return `<line class="chart-grid" x1="${left}" y1="${yy}" x2="${right}" y2="${yy}"/><text class="chart-label" x="${left-10}" y="${yy+4}" text-anchor="end">${dur(Math.round(value))}</text>`}).join('');
  const yearTicks=[minY,1980,1990,2000,2010,2020,maxY].filter((v,i,a)=>v>=minY&&v<=maxY&&a.indexOf(v)===i).map(year=>{const xx=left+(year-minY)/(maxY-minY)*(right-left);return `<text class="chart-label" x="${xx}" y="260" text-anchor="middle">${year}</text>`}).join('');
  const dots=(key,klass)=>rows.map(row=>`<circle class="${klass}" tabindex="0" role="img" aria-label="${row.year}年：${dur(Math.round(row[key]))}" cx="${x(row)}" cy="${y(row[key])}" r="3"><title>${row.year}：${dur(Math.round(row[key]))}</title></circle>`).join('');
  return `<svg viewBox="0 0 700 275" role="img" aria-label="每年平均及中位有效時間折線圖">${grids}<polyline class="observed-line" points="${points(keyA)}"/><polyline class="warning-line" points="${points(keyB)}"/>${dots(keyA,'observed-dot')}${dots(keyB,'warning-dot')}${yearTicks}</svg><div class="legend"><span class="observed">平均</span><span class="warnings">中位數</span></div>`;
}
function renderClimate(c){const rows=c.annual,minY=rows[0].year,maxY=rows.at(-1).year,maxD=Math.max(...rows.map(x=>x.thunderstorm_days)),maxW=Math.max(...rows.map(x=>x.warning_series));const pts=(key,max)=>rows.map(x=>`${(x.year-minY)/(maxY-minY)*600},${220-x[key]/max*200}`).join(' ');$('#climateLines').innerHTML=`<svg viewBox="0 0 600 240" role="img" aria-label="年度雷暴日數及警告系列標準化趨勢"><line class="axis" x1="0" y1="220" x2="600" y2="220"/><polyline class="observed-line" points="${pts('thunderstorm_days',maxD)}"/><polyline class="warning-line" points="${pts('warning_series',maxW)}"/></svg>`;$('#climatePeriods').innerHTML=micro(c.pearson_by_period.map(x=>[x.period,x.pearson??'—']));$('#climateNote').textContent=`全期Pearson相關系數：${c.pearson_all}。${c.note}`;const maxO=Math.max(...c.monthly_thunderstorm_day_normals_1991_2020),maxWarn=Math.max(...c.monthly_warning_series_average_1991_2020);$('#monthlyCompare').innerHTML=months.map((m,i)=>{const label=`${m}：雷暴日 ${c.monthly_thunderstorm_day_normals_1991_2020[i]}；警告 ${c.monthly_warning_series_average_1991_2020[i]}組`;return `<div class="month-pair" tabindex="0" role="img" aria-label="${label}" title="${label}"><i class="observed" style="--observed:${c.monthly_thunderstorm_day_normals_1991_2020[i]/maxO*100}%"></i><i class="warnings" style="--warnings:${c.monthly_warning_series_average_1991_2020[i]/maxWarn*100}%"></i><span>${i+1}</span></div>`}).join('')}
init().catch(e=>{$('#analysisLoading').textContent=`分析載入失敗：${e.message}`});
